In [1]:
# Libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [7]:
import math
from operator import itemgetter, indexOf

In [3]:
%matplotlib inline
sns.set_style("darkgrid")

In [4]:
from sklearn.datasets import load_iris

In [5]:
# Dataset
dataset = load_iris()

In [6]:
# X
X = dataset.data
X.shape

(150, 4)

In [7]:
# y
y = dataset.target
y.shape

(150,)

In [8]:
# Splitting data
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=10)

In [8]:
def euclidianDistance(d1, d2):
    dist = 0
    for i in range(len(d1)):
        dist += pow((d1[i] - d2[i]), 2)
    return math.sqrt(dist)

In [9]:
def getNeighbour(item, data, k):
    distances = []
    for i in range(len(data)):
        dist = euclidianDistance(item, data[i])
        distances.append((data[i], dist))
    distances.sort(key=itemgetter(1))
    neighbour = []
    for j in range(k):
        neighbour.append(distances[j][0])
    return neighbour

In [10]:
def getResponse(neighbours, data, result):
    classVotes = {}
    for i in range(len(neighbours)):
        response = result[data.tolist().index(neighbours[i].tolist())]
        if response in classVotes:
            classVotes[response] += 1
        else:
            classVotes[response] = 1
    sortedVotes = sorted(classVotes.items(), key=itemgetter(1), reverse=True)
    return sortedVotes[0][0]

In [11]:
y_pred=[]
k = 3
for x in range(len(y_test)):
    neighbors = getNeighbour(X_test[x], X_train, k)
    result = getResponse(neighbors, X_train, y_train)
    y_pred.append(result)

In [12]:
np.array(y_pred)

array([0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1,
       0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1,
       0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1,
       0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1,
       1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1,
       0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1,
       1, 1])

In [13]:
y_test

array([0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1,
       1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1,
       0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1,
       0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1,
       0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1,
       1, 1])

In [14]:
# Confusion matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
cm

array([[87, 10],
       [11, 92]], dtype=int64)

In [16]:
def classPresent(Y):
    elem = []
    for i in range(len(Y)):
        if Y[i] not in elem:
            elem.append(Y[i])
    elem.sort()        
    return elem

In [1]:
import numpy as np
import pandas as pd
from sklearn.datasets import make_classification

In [2]:
X, y = make_classification(n_samples=1000, n_features=20, n_informative=18, n_classes=2, n_clusters_per_class=2, random_state=101)

In [3]:
X.shape

(1000, 20)

In [4]:
y.shape

(1000,)

In [5]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=101)

In [6]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)