In [1]:
import numpy as np
import pandas as pd
from sklearn.datasets import make_regression

In [45]:
X, y = make_regression(n_samples=1000, n_features=100, n_informative=97, noise=15, random_state=101)

In [46]:
X.shape

(1000, 100)

In [47]:
y.shape

(1000,)

In [48]:
X = np.concatenate((np.ones((len(X), 1)), X), axis=1)
X.shape

(1000, 101)

In [49]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=101)

In [50]:
coeff = np.dot(np.linalg.inv(np.dot(X_train.T, X_train)), np.dot(X_train.T, y_train))
coeff

array([ 0.61954859, 40.12214788, 51.37621898, 70.04653767,  5.4207403 ,
       53.13621431, 56.30892212, 29.5668639 ,  0.70389605, 34.53201405,
        6.89098894, 59.50981145, 31.73775977, 84.56751427, 93.61989773,
       43.47921187, 27.88128842,  5.14784674, 98.66863882,  7.97036199,
       81.4509788 , 29.12726047, 25.07545551, -0.49861745, 41.64788924,
       64.87899851, 20.56806633, 43.64356352, 17.06366561, 61.19286003,
       36.80993503, 24.59990322, 84.7651244 ,  1.91456339, 44.23055804,
       21.1296588 , 46.82822808, 74.84495423, 74.478939  , 21.1254669 ,
       93.7499781 , 49.38310443, 49.18865728, 55.58651127, 65.14293967,
       61.58346958, 15.78993926, 84.5245974 , 77.62958471, 70.52169254,
       78.24460108, 98.87673308, 55.98552831, 68.54659374, 36.5673176 ,
       22.47931155, 99.59538122, -0.26079123, 58.6711608 , 61.94159725,
       47.1157728 , 60.49864113, 52.15068589, 85.58727128, 93.72042876,
       39.83145644, 47.34778284, 12.59129543, 93.07690905, 42.41

In [51]:
y_pred = np.dot(X_test, coeff)
y_pred

array([ 7.09381311e+02,  2.50305536e+02, -7.08781941e+02,  6.85592635e+02,
       -3.49176952e+02, -4.29980957e+02, -5.90537165e+02, -4.12496063e+02,
       -7.44460864e+02,  3.07998301e+02, -2.32107086e+02, -1.34164050e+02,
       -2.21336252e+02, -6.29247585e+02,  5.05003102e+02,  4.71988758e+02,
       -2.88969424e+02,  5.13949978e+02, -3.88246109e+02, -5.07811010e+02,
       -5.95435847e+02,  6.15742591e+02,  5.08110159e+02,  1.49238409e+01,
       -5.03503522e+02,  1.13106251e+02, -2.59095766e+02, -3.53980849e+02,
       -3.45203315e+02, -1.58322340e+02,  3.39297112e+02, -1.42420539e+02,
       -3.76486648e+02, -1.02660764e+02, -4.42263623e+02, -8.38751672e+02,
        1.16373352e+03, -2.86066729e+02, -1.51121520e+02,  6.29713948e+02,
       -6.16475619e+02, -1.06995008e+02,  1.81699884e+03,  8.92912748e+01,
       -4.04645330e+02, -8.51452549e+01, -5.70986124e+02,  2.56851378e+01,
       -8.53890640e+02,  1.93995549e+02,  2.74606868e+02, -3.07651777e+02,
       -6.62533844e+01, -

In [52]:
y_test

array([ 6.92640477e+02,  2.51403177e+02, -6.81938785e+02,  7.09654939e+02,
       -3.59203335e+02, -4.14044411e+02, -5.78041558e+02, -3.93897404e+02,
       -7.51853614e+02,  3.14392154e+02, -2.39506564e+02, -1.54420702e+02,
       -2.46995291e+02, -6.22517425e+02,  5.01915279e+02,  4.87049608e+02,
       -3.20498957e+02,  5.37642242e+02, -4.00872408e+02, -5.20209718e+02,
       -5.90021004e+02,  6.51124685e+02,  5.03759518e+02,  2.33605244e+01,
       -5.26932924e+02,  1.27374001e+02, -2.43917504e+02, -3.54643326e+02,
       -3.49286333e+02, -1.58605506e+02,  3.42742874e+02, -1.65162206e+02,
       -3.76257197e+02, -1.03636900e+02, -4.49885985e+02, -8.32870677e+02,
        1.13198226e+03, -2.82366076e+02, -1.51549921e+02,  6.27768517e+02,
       -6.45859637e+02, -1.29176489e+02,  1.82293719e+03,  7.40147392e+01,
       -4.02909342e+02, -8.56911917e+01, -5.72281765e+02,  4.40752350e+01,
       -8.41798547e+02,  1.72795754e+02,  2.67901363e+02, -3.22335415e+02,
       -8.84107680e+01, -

In [53]:
u = np.sum((y_test - y_pred) ** 2) / float(len(y_test))
v = np.sum((y_test - y_test.mean()) ** 2) / float(len(y_test))
r2 = 1 - (u/v)

In [54]:
r2

0.9991162291120661

In [55]:
from sklearn.metrics import mean_squared_error
mean_squared_error(y_test, y_pred)

250.96743306256715

In [56]:
# Estimate linear regression coefficients using stochastic gradient descent
def coefficients_sgd(X, y, coeff, l_rate, n_epoch):
    m, n = X.shape
    # coef = np.zeros(n)
    coef = coeff
    for epoch in range(n_epoch):
        sum_error = 0.0
        for i in range(m):
            yhat = np.dot(X[i], coef)
            error = y[i] - yhat
            sum_error += (error**2)
            for j in range(n):
                coef[j] += (l_rate * error * X[i, j])
        print('---> epoch=%d, lrate=%.3f, error=%.3f' % (epoch, l_rate, sum_error))
    return coef

In [57]:
# Calculate coefficients
l_rate = 0.001
n_epoch = 10

In [58]:
coef = coefficients_sgd(X_train, y_train, coeff, l_rate, n_epoch)
coef

---> epoch=0, lrate=0.001, error=167153.132
---> epoch=1, lrate=0.001, error=167829.253
---> epoch=2, lrate=0.001, error=168188.539
---> epoch=3, lrate=0.001, error=168344.959
---> epoch=4, lrate=0.001, error=168414.885
---> epoch=5, lrate=0.001, error=168447.827
---> epoch=6, lrate=0.001, error=168464.110
---> epoch=7, lrate=0.001, error=168472.483
---> epoch=8, lrate=0.001, error=168476.928
---> epoch=9, lrate=0.001, error=168479.352
---> epoch=10, lrate=0.001, error=168480.703
---> epoch=11, lrate=0.001, error=168481.472
---> epoch=12, lrate=0.001, error=168481.916
---> epoch=13, lrate=0.001, error=168482.177
---> epoch=14, lrate=0.001, error=168482.332
---> epoch=15, lrate=0.001, error=168482.426
---> epoch=16, lrate=0.001, error=168482.483
---> epoch=17, lrate=0.001, error=168482.518
---> epoch=18, lrate=0.001, error=168482.540
---> epoch=19, lrate=0.001, error=168482.554
---> epoch=20, lrate=0.001, error=168482.563
---> epoch=21, lrate=0.001, error=168482.568
---> epoch=22, lrate

---> epoch=192, lrate=0.001, error=168482.579
---> epoch=193, lrate=0.001, error=168482.579
---> epoch=194, lrate=0.001, error=168482.579
---> epoch=195, lrate=0.001, error=168482.579
---> epoch=196, lrate=0.001, error=168482.579
---> epoch=197, lrate=0.001, error=168482.579
---> epoch=198, lrate=0.001, error=168482.579
---> epoch=199, lrate=0.001, error=168482.579
---> epoch=200, lrate=0.001, error=168482.579
---> epoch=201, lrate=0.001, error=168482.579
---> epoch=202, lrate=0.001, error=168482.579
---> epoch=203, lrate=0.001, error=168482.579
---> epoch=204, lrate=0.001, error=168482.579
---> epoch=205, lrate=0.001, error=168482.579
---> epoch=206, lrate=0.001, error=168482.579
---> epoch=207, lrate=0.001, error=168482.579
---> epoch=208, lrate=0.001, error=168482.579
---> epoch=209, lrate=0.001, error=168482.579
---> epoch=210, lrate=0.001, error=168482.579
---> epoch=211, lrate=0.001, error=168482.579
---> epoch=212, lrate=0.001, error=168482.579
---> epoch=213, lrate=0.001, error

---> epoch=393, lrate=0.001, error=168482.579
---> epoch=394, lrate=0.001, error=168482.579
---> epoch=395, lrate=0.001, error=168482.579
---> epoch=396, lrate=0.001, error=168482.579
---> epoch=397, lrate=0.001, error=168482.579
---> epoch=398, lrate=0.001, error=168482.579
---> epoch=399, lrate=0.001, error=168482.579
---> epoch=400, lrate=0.001, error=168482.579
---> epoch=401, lrate=0.001, error=168482.579
---> epoch=402, lrate=0.001, error=168482.579
---> epoch=403, lrate=0.001, error=168482.579
---> epoch=404, lrate=0.001, error=168482.579
---> epoch=405, lrate=0.001, error=168482.579
---> epoch=406, lrate=0.001, error=168482.579
---> epoch=407, lrate=0.001, error=168482.579
---> epoch=408, lrate=0.001, error=168482.579
---> epoch=409, lrate=0.001, error=168482.579
---> epoch=410, lrate=0.001, error=168482.579
---> epoch=411, lrate=0.001, error=168482.579
---> epoch=412, lrate=0.001, error=168482.579
---> epoch=413, lrate=0.001, error=168482.579
---> epoch=414, lrate=0.001, error

---> epoch=573, lrate=0.001, error=168482.579
---> epoch=574, lrate=0.001, error=168482.579
---> epoch=575, lrate=0.001, error=168482.579
---> epoch=576, lrate=0.001, error=168482.579
---> epoch=577, lrate=0.001, error=168482.579
---> epoch=578, lrate=0.001, error=168482.579
---> epoch=579, lrate=0.001, error=168482.579
---> epoch=580, lrate=0.001, error=168482.579
---> epoch=581, lrate=0.001, error=168482.579
---> epoch=582, lrate=0.001, error=168482.579
---> epoch=583, lrate=0.001, error=168482.579
---> epoch=584, lrate=0.001, error=168482.579
---> epoch=585, lrate=0.001, error=168482.579
---> epoch=586, lrate=0.001, error=168482.579
---> epoch=587, lrate=0.001, error=168482.579
---> epoch=588, lrate=0.001, error=168482.579
---> epoch=589, lrate=0.001, error=168482.579
---> epoch=590, lrate=0.001, error=168482.579
---> epoch=591, lrate=0.001, error=168482.579
---> epoch=592, lrate=0.001, error=168482.579
---> epoch=593, lrate=0.001, error=168482.579
---> epoch=594, lrate=0.001, error

---> epoch=775, lrate=0.001, error=168482.579
---> epoch=776, lrate=0.001, error=168482.579
---> epoch=777, lrate=0.001, error=168482.579
---> epoch=778, lrate=0.001, error=168482.579
---> epoch=779, lrate=0.001, error=168482.579
---> epoch=780, lrate=0.001, error=168482.579
---> epoch=781, lrate=0.001, error=168482.579
---> epoch=782, lrate=0.001, error=168482.579
---> epoch=783, lrate=0.001, error=168482.579
---> epoch=784, lrate=0.001, error=168482.579
---> epoch=785, lrate=0.001, error=168482.579
---> epoch=786, lrate=0.001, error=168482.579
---> epoch=787, lrate=0.001, error=168482.579
---> epoch=788, lrate=0.001, error=168482.579
---> epoch=789, lrate=0.001, error=168482.579
---> epoch=790, lrate=0.001, error=168482.579
---> epoch=791, lrate=0.001, error=168482.579
---> epoch=792, lrate=0.001, error=168482.579
---> epoch=793, lrate=0.001, error=168482.579
---> epoch=794, lrate=0.001, error=168482.579
---> epoch=795, lrate=0.001, error=168482.579
---> epoch=796, lrate=0.001, error

---> epoch=956, lrate=0.001, error=168482.579
---> epoch=957, lrate=0.001, error=168482.579
---> epoch=958, lrate=0.001, error=168482.579
---> epoch=959, lrate=0.001, error=168482.579
---> epoch=960, lrate=0.001, error=168482.579
---> epoch=961, lrate=0.001, error=168482.579
---> epoch=962, lrate=0.001, error=168482.579
---> epoch=963, lrate=0.001, error=168482.579
---> epoch=964, lrate=0.001, error=168482.579
---> epoch=965, lrate=0.001, error=168482.579
---> epoch=966, lrate=0.001, error=168482.579
---> epoch=967, lrate=0.001, error=168482.579
---> epoch=968, lrate=0.001, error=168482.579
---> epoch=969, lrate=0.001, error=168482.579
---> epoch=970, lrate=0.001, error=168482.579
---> epoch=971, lrate=0.001, error=168482.579
---> epoch=972, lrate=0.001, error=168482.579
---> epoch=973, lrate=0.001, error=168482.579
---> epoch=974, lrate=0.001, error=168482.579
---> epoch=975, lrate=0.001, error=168482.579
---> epoch=976, lrate=0.001, error=168482.579
---> epoch=977, lrate=0.001, error

array([ 0.67686725, 40.31074356, 51.47174893, 70.01088206,  5.28581753,
       53.39280751, 56.25328501, 29.70213258,  0.63622999, 34.48963015,
        6.64599683, 59.64590885, 31.67850726, 84.44891599, 93.71604266,
       43.50435766, 28.05639672,  5.27241541, 98.60832314,  8.08818115,
       81.47336822, 29.3044376 , 25.12985706, -0.49399726, 41.69279082,
       64.78179973, 20.64309833, 43.43326096, 16.88671575, 60.94580996,
       36.64839065, 24.68177464, 84.95549094,  1.69643128, 44.13369107,
       21.17033543, 46.87635837, 74.86571685, 74.56428506, 21.30150178,
       93.76599208, 49.35294055, 49.26224266, 55.45901521, 65.02584419,
       61.58777873, 15.88400026, 84.65167725, 77.6816942 , 70.45758572,
       78.14775978, 98.72088423, 55.91561088, 68.59273591, 36.53137885,
       22.6975787 , 99.51625118, -0.19408691, 58.62549851, 61.89863069,
       46.96788709, 60.63589663, 52.08985867, 85.66579058, 93.61242644,
       39.900379  , 47.29911116, 12.46726605, 93.24553159, 42.56

In [59]:
y_predd = np.dot(X_test, coef)
y_predd

array([ 7.07711308e+02,  2.50898245e+02, -7.08637750e+02,  6.85894945e+02,
       -3.48004217e+02, -4.28704600e+02, -5.89150253e+02, -4.11469581e+02,
       -7.43384695e+02,  3.09245228e+02, -2.31676255e+02, -1.33710880e+02,
       -2.21123404e+02, -6.28508763e+02,  5.06063224e+02,  4.70486719e+02,
       -2.89899923e+02,  5.13454478e+02, -3.86504202e+02, -5.07759201e+02,
       -5.96044337e+02,  6.16344666e+02,  5.06598908e+02,  1.68652279e+01,
       -5.03349079e+02,  1.13463399e+02, -2.57481471e+02, -3.54693380e+02,
       -3.47141052e+02, -1.58045772e+02,  3.37290268e+02, -1.41643399e+02,
       -3.77130129e+02, -1.04133151e+02, -4.41873779e+02, -8.38534886e+02,
        1.16358393e+03, -2.87471836e+02, -1.52822733e+02,  6.28297874e+02,
       -6.16170303e+02, -1.07792897e+02,  1.81502283e+03,  8.94073358e+01,
       -4.05875996e+02, -8.74309341e+01, -5.71025753e+02,  2.73577887e+01,
       -8.53615428e+02,  1.94405675e+02,  2.74572217e+02, -3.07648560e+02,
       -6.68582025e+01, -

In [60]:
y_test

array([ 6.92640477e+02,  2.51403177e+02, -6.81938785e+02,  7.09654939e+02,
       -3.59203335e+02, -4.14044411e+02, -5.78041558e+02, -3.93897404e+02,
       -7.51853614e+02,  3.14392154e+02, -2.39506564e+02, -1.54420702e+02,
       -2.46995291e+02, -6.22517425e+02,  5.01915279e+02,  4.87049608e+02,
       -3.20498957e+02,  5.37642242e+02, -4.00872408e+02, -5.20209718e+02,
       -5.90021004e+02,  6.51124685e+02,  5.03759518e+02,  2.33605244e+01,
       -5.26932924e+02,  1.27374001e+02, -2.43917504e+02, -3.54643326e+02,
       -3.49286333e+02, -1.58605506e+02,  3.42742874e+02, -1.65162206e+02,
       -3.76257197e+02, -1.03636900e+02, -4.49885985e+02, -8.32870677e+02,
        1.13198226e+03, -2.82366076e+02, -1.51549921e+02,  6.27768517e+02,
       -6.45859637e+02, -1.29176489e+02,  1.82293719e+03,  7.40147392e+01,
       -4.02909342e+02, -8.56911917e+01, -5.72281765e+02,  4.40752350e+01,
       -8.41798547e+02,  1.72795754e+02,  2.67901363e+02, -3.22335415e+02,
       -8.84107680e+01, -

In [61]:
u = np.sum((y_test - y_predd) ** 2) / float(len(y_test))
v = np.sum((y_test - y_test.mean()) ** 2) / float(len(y_test))
r2 = 1 - (u/v)

In [62]:
r2

0.9991264278918193

In [63]:
from sklearn.metrics import mean_squared_error
mean_squared_error(y_test, y_predd)

248.07125079407942

In [64]:
y.mean()

6.503957731888289