In [1]:
import numpy as np
import pandas as pd
from sklearn.datasets import make_classification

In [2]:
X, y = make_classification(n_samples=1000, n_features=20, n_informative=18, n_classes=2, n_clusters_per_class=2, random_state=101)

In [3]:
X.shape

(1000, 20)

In [4]:
y.shape

(1000,)

In [5]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=101)

In [6]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [7]:
class LogisticRegression():
    """
    Logistic Regression.
    (Maximum 2 classes)

    Parameters
    ----------
    fit_intercept : boolean, optional, default True
        whether to calculate the intercept for this model. If set
        to False, no intercept will be used in calculations
        (e.g. data is expected to be already centered).
        
    copy_X : boolean, optional, default True
        If True, X will be copied; else, it may be overwritten.


    Attributes
    ----------
    coef_ : array, shape (n_features, ) or (n_targets, n_features)
        Estimated coefficients for the linear regression problem.
        If multiple targets are passed during the fit (y 2D), this
        is a 2D array of shape (n_targets, n_features), while if only
        one target is passed, this is a 1D array of length n_features.

    intercept_ : array
        Independent term in the linear model.

    Examples
    --------
    >>> import numpy as np
    >>> class LinearRegression():
            ...
    >>> X = np.array([[1, 1], [1, 2], [2, 2], [2, 3]])
    >>> y = [1]
    >>> reg = LinearRegression().fit(X, y)
    >>> reg.coef_
    array([1., 2.])
    >>> reg.intercept_
    3.0000...
    >>> reg.predict(np.array([[3, 5]]))
    array([1.])

    """

    def __init__(self, fit_intercept=True, copy_X=True):
        self.fit_intercept = fit_intercept
        self.copy_X = copy_X
    
    
    
    def fit(self, x, y):
        """
        Fit linear model.

        Parameters
        ----------
        X : array-like or sparse matrix, shape (n_samples, n_features)
            Training data

        y : array_like, shape (n_samples, n_targets)
            Target values.

        Returns
        -------
        self : returns an instance of self.
        """
        classes = []
        for _i in range(len(y)):
            if y[_i] not in classes:
                classes.append(y[_i])
        
        if len(classes) > 2:
            raise Warning("Multinomial class present")
        
        
        if self.copy_X:
            X = x.copy()
        else:
            X = x
        
        
        self.coef_ = np.dot(np.linalg.inv(np.dot(X.T, X)), np.dot(X.T, y))
        
        
        if self.fit_intercept:
            self.intercept_ = np.array([np.mean(y) - np.dot(np.mean(X, axis=0), self.coef_)])
        else:
            self.intercept_ = np.array([0])
        
        return self
        
        
        
    def predict(self, X):
        """
        Predict using the linear model

        Parameters
        ----------
        X : array_like or sparse matrix, shape (n_samples, n_features)
        Samples.
        
        Returns
        -------
        C : array, shape (n_samples,)
        Returns predicted values.
        """
        _pred = np.dot(X, self.coef_) + self.intercept_
        _pred = 1.0 / (1.0 + np.exp(-_pred))
        _predict = np.zeros((len(_pred)), dtype=int)
        _threshold = (_pred.min() + _pred.max())/2
        for _i in range(len(_pred)):
            if _pred[_i] > _threshold:
                _predict[_i] = 1
        return _predict

In [8]:
model = LogisticRegression()

In [9]:
model.fit(X_train, y_train)

In [10]:
y_pred = model.predict(X_test)
y_pred

array([1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1,
       0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1,
       1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1,
       1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0,
       0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1,
       0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1,
       1, 1])

In [11]:
model.intercept_

array([0.27947753])

In [12]:
model.coef_

array([-1.421875  , -0.28125   , -0.125     ,  1.5       , -1.875     ,
       -0.21875   ,  0.25      , -0.125     , -0.125     , -1.70703125,
        0.796875  ,  0.625     , -0.71875   ,  0.625     , -0.1875    ,
        1.5       ,  2.25      , -0.125     ,  0.5625    , -0.875     ])

In [13]:
from sklearn.metrics import confusion_matrix

In [14]:
cm = confusion_matrix(y_test, y_pred)
cm

array([[60, 37],
       [10, 93]], dtype=int64)

In [15]:
(cm[0][0]+cm[1][1])/len(y_test)

0.765