In [1]:
import numpy as np
import pandas as pd
from sklearn.datasets import make_regression

In [2]:
X, y = make_regression(n_samples=100, n_features=10, n_informative=7, noise=15, random_state=101)

In [3]:
X.shape

(100, 10)

In [4]:
y.shape

(100,)

In [5]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=101)

In [6]:
class LinearRegression():
    """
    Simple Linear Regression.

    Parameters
    ----------
    fit_intercept : boolean, optional, default True
        whether to calculate the intercept for this model. If set
        to False, no intercept will be used in calculations
        (e.g. data is expected to be already centered).


    Attributes
    ----------
    coef_ : array, shape (n_features, ) or (n_targets, n_features)
        Estimated coefficients for the linear regression problem.
        If multiple targets are passed during the fit (y 2D), this
        is a 2D array of shape (n_targets, n_features), while if only
        one target is passed, this is a 1D array of length n_features.

    intercept_ : array
        Independent term in the linear model.

    Examples
    --------
    >>> import numpy as np
    >>> class LinearRegression():
            ...
    >>> X = np.array([[1, 1], [1, 2], [2, 2], [2, 3]])
    >>> # y = 1 * x_0 + 2 * x_1 + 3
    >>> y = np.dot(X, np.array([1, 2])) + 3
    >>> reg = LinearRegression().fit(X, y)
    >>> reg.coef_
    array([1., 2.])
    >>> reg.intercept_
    3.0000...
    >>> reg.predict(np.array([[3, 5]]))
    array([16.])

    """

    def __init__(self, fit_intercept=True):
        self.fit_intercept = fit_intercept
    
    
    
    def fit(self, X, y):
        """
        Fit linear model.

        Parameters
        ----------
        X : array-like or sparse matrix, shape (n_samples, n_features)
            Training data

        y : array_like, shape (n_samples, n_targets)
            Target values.

        Returns
        -------
        self : returns an instance of self.
        """
        self.coef_ = np.dot(np.linalg.inv(np.dot(X.T, X)), np.dot(X.T, y))
        
        if self.fit_intercept:
            self.intercept_ = np.mean(y) - np.dot(np.mean(X, axis=0), self.coef_)
        else:
            self.intercept_ = 0
        
        return self
        
        
        
    def predict(self, X):
        """
        Predict using the linear model

        Parameters
        ----------
        X : array_like or sparse matrix, shape (n_samples, n_features)
        Samples.
        
        Returns
        -------
        C : array, shape (n_samples,)
        Returns predicted values.
        """
        return np.dot(X, self.coef_) + self.intercept_ 

In [7]:
model = LinearRegression(fit_intercept=False)

In [8]:
model.fit(X_train, y_train)

In [9]:
y_pred = model.predict(X_test)
y_pred

array([ -85.17225599, -148.25394251,  -82.25805153, -126.06552119,
       -263.90233207,  185.96451845, -318.96901139,   46.76700499,
        103.86494961, -204.40329607,    4.68070966,   52.06632485,
        145.59781783,  109.88883274,  175.43004808,   63.63163835,
       -155.8602804 ,  126.52385261,  -54.29585915, -186.98656077])

In [10]:
model.intercept_

0

In [11]:
model.coef_

array([91.77780593, 44.85931598, 59.06409957, 19.52408124, -1.99296354,
        3.84298463, 84.91039697, -1.59262994, 93.93059401, -2.31692525])

In [12]:
from sklearn import metrics

In [13]:
mae = metrics.mean_absolute_error(y_test, y_pred)
mse = metrics.mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)
r2 = metrics.r2_score(y_test, y_pred)

In [14]:
err = pd.DataFrame([mae, mse, rmse, r2], ['mean absolute error', 'mean squared error', 'root mean squared error', 'r^2 score'], ['errors'])
err

errors
mean absolute error       15.563163
mean squared error       351.434663
root mean squared error   18.746591
r^2 score                  0.982897