In [1]:
# Libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [11]:
import math

In [3]:
%matplotlib inline
sns.set_style("darkgrid")

In [4]:
from sklearn.datasets import load_iris

In [5]:
# Dataset
dataset = load_iris()

In [6]:
# X
X = dataset.data
X.shape

(150, 4)

In [7]:
# y
y = dataset.target
y.shape

(150,)

In [8]:
# Splitting data
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=101)

In [12]:
a,b = X_train.shape
a,b

(800, 20)

In [13]:
elem = []
for i in range(a):
    if y_train[i] not in elem:
        elem.append(y_train[i])
elem.sort()        
elem

[0, 1]

In [14]:
def mean(numbers):
    return sum(numbers)/float(len(numbers))

def stdev(numbers):
    avg = mean(numbers)
    variance = sum([pow(x-avg,2) for x in numbers])/float(len(numbers)-1)
    return math.sqrt(variance)

In [15]:
summr = {}
for j in elem:
    elemv = []
    lister = []
    for i in range(a):
        if y_train[i] == elem[j]:
            elemv.append(X_train[i])
    for k in range(b):
        lists = []
        for l in range(len(elemv)):
            lists.append(elemv[l][k])
        lister.append((mean(lists), stdev(lists)))
    summr[elem[j]] = (lister)
summr

{0: [(0.5515994497007654, 0.14448783977571542),
  (0.6056070306320824, 0.14078350559829922),
  (0.4903768025693711, 0.13187398366409453),
  (0.4479533232944955, 0.13368063837956776),
  (0.5461354540047867, 0.15406512346852064),
  (0.5364604517586504, 0.16236551725993387),
  (0.4484306676721869, 0.17272163170362045),
  (0.541167240321758, 0.16859856460063596),
  (0.5594933180554683, 0.15265722807598786),
  (0.4468390669823621, 0.14399522830386974),
  (0.5149284714284483, 0.15608793248235706),
  (0.5209769565566673, 0.1760069541886387),
  (0.5272936197895637, 0.15901485938088497),
  (0.4859762261345466, 0.13894973406630493),
  (0.4353831430186983, 0.1525415088519447),
  (0.4694320511523903, 0.15921039712362636),
  (0.5421476331386978, 0.1416434289691586),
  (0.4788417280922277, 0.11512127941215837),
  (0.4955396106730509, 0.18096068435243362),
  (0.5377634443144046, 0.13994749459275602)],
 1: [(0.5007128189579675, 0.13251240696401695),
  (0.5282195175095326, 0.16217467971381266),
  (0.50

In [16]:
def calculateProbability(x, mean, stdev):
    exponent = math.exp(-(math.pow(x-mean,2)/(2*math.pow(stdev,2))))
    return (1 / (math.sqrt(2*math.pi) * stdev)) * exponent

In [17]:
c, d = X_test.shape
c, d

(200, 20)

In [18]:
lister = []
for i in range(c):
    lists = []
    for k in elem:
        elemv = 1
        for j in range(d):
            elemv *= (calculateProbability(X_test[i][j], summr[elem[k]][j][0], summr[elem[k]][j][1]))
        lists.append(elemv)
    lister.append(lists)

In [19]:
lister

[[15.364419911807296, 13.636796152812996],
 [1229.7711651265688, 412.26388506313793],
 [43760.72855961241, 75779.68813285921],
 [2359332.650385608, 10244821.392202396],
 [511.19918851803664, 16.923026816826642],
 [28926.427037682177, 1923.1316070948417],
 [28652.288312228324, 39862.77711199301],
 [219128.0016659842, 127175.36633634189],
 [6495.437358859233, 7024.825482702503],
 [55444.969219719555, 9438.165363998143],
 [78521.94117086091, 288201.7015226138],
 [409.15257745676695, 6490.858371579425],
 [0.39899057469393934, 16.60622851064466],
 [1676534.7241236775, 3132912.307391743],
 [14109.23282370573, 159981.05404867537],
 [0.11092638471217477, 0.6969400126644719],
 [6786252.766759922, 8843662.448994385],
 [314.03970527856706, 1670.0485921955847],
 [33155.691111746404, 19818.707806015856],
 [189957.3614820132, 46546.9741792436],
 [71993.0557478753, 252824.9199398867],
 [102894.16137257419, 61749.534544250404],
 [4360690.222527337, 3590408.347657563],
 [16818.167733812523, 22837.32614

In [20]:
y_pred = []
for i in range(c):
    num, val = 0, None
    for j in range(len(elem)):
        if lister[i][j] > num:
            num = lister[i][j]
            val = elem[j]
    y_pred.append(val)

In [21]:
np.array(y_pred)

array([0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0,
       0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1,
       0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1,
       0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1,
       1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1,
       1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1,
       0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0,
       1, 0])

In [22]:
y_test

array([0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1,
       1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1,
       0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1,
       0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1,
       0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1,
       1, 1])

In [23]:
# Confusion matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
cm

array([[72, 25],
       [23, 80]], dtype=int64)

In [1]:
import numpy as np
import pandas as pd
from sklearn.datasets import make_classification

In [2]:
X, y = make_classification(n_samples=1000, n_features=20, n_informative=18, n_classes=2, n_clusters_per_class=2, random_state=101)

In [3]:
X.shape

(1000, 20)

In [4]:
y.shape

(1000,)

In [5]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=101)

In [6]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)